export const JtoQuotes = [
  `January 1st: Global Family Day`,
  `January 4th: World Braille Day`,
  `January 11th: International Thank You Day`,
  `January 30th: World Leprosy Day`,
  `Febrary 12th: Darwin Day`,
  `Febrary 21st: International Mother Language Day`,
  `Febrary 22nd: World Thinking Day`,
  `March 1st: International Day of the Seal`,
  `March 8th: International Woman's Day`,
  `March 15th: Red Nose Day`,
  `March 20th: World Frog Day`,
  `March 21st: World Water Day`,
  `March 22nd: World Water Day`,
  `March 23rd: World Meteorological Day`,
  `March 30th: Earth Hour`,
  `April 2nd: International Children's Day`,
  `April 7th: World Health Day`,
  `April 17th: International Special Librarian's Day`,
  `April 21st: International Creativity and Innovation Day`,
  `April 22nd: Earth Day`,
  `April 23rd: World Book Day`,
  `April 25th: World Malaria Day`,
  `April 25th: World Penguin Day`,
  `May 3rd: World Press Freedom Day`,
  `May 5th: International Midwives Day`,
  `May 8th: World Red Cross Day`,
  `May 10th: World Lupus Day`,
  `May 12th: International Nurses Day`,
  `May 13th: IEEE Global Engineering Day`,
  `May 15th: International Day of Families`,
  `May 18th: International Museum Day`,
  `May 21st: World Day for Cultural Diversity`,
  `May 22nd: International Day for Biological Diversity`,
  `May 23rd: World Turtle Day`,
  `May 24th: World Schizophrenia Day`,
  `May 25th: Towel Day`,
  `May 31st: World No-Tobacco Day`,
  `June 3rd: World Bicycle Day`,
  `June 5th: World Environment Day`,
  `June 8th: World Ocean Day`,
  `June 14th: World Blood Donor Day`,
  `June 16th: International Day of the African Child`,
  `June 17th: World Day to Combat Desertification & Drought`,
  `June 20th: World Refugee Day`,
  `June 21st: International Yoga Day`,
  `June 26th: International Day Against Drug Abuse and Trafficking`,
  `July 11th: World Population Day`,
  `July 16th: World Snake Day`,
  `July 28th: World Hepatitis Day`,
  `August 4th: International Friendship Day`,
  `August 8th: Universal & International Infinity Day`,
  `August 9th: International Day of the World's Indigenous People`,
  `August 10th: International Biodiesel Day`,
  `August 12th: International Youth Day`,
  `August 13th: International Lefthanders Day`,
  `August 14th: World Lizard Day`,
  `August 23rd: International Day for the Remembrance of the Slave Trade & its Abolition`,
  `September 8th: International Literacy Day`,
  `September 13th: International Chocolate Day`,
  `September 15th: International Day of Democracy`,
  `September 15th: Software Freedom Day`,
  `September 16th: International Day for Preservation of the Ozone Layer`,
  `September 19th: Talk Like a Pirate Day`,
  `September 21st: World Gratitude Day`,
  `September 22nd: World Car-Free Day`,
  `September 29th: Inventors Day`,
  `October 1st: International Music Day`,
  `October 2nd: World Farm Animals Day`,
  `October 3rd: World Temperance Day`,
  `October 4th: World Animal Day`,
  `October 5th: World Teachers Day`,
  `October 10th: World Mental Health Day`,
  `October 16th: World Food Day`,
  `October 17th: International Day for the Eradication of Poverty`,
  `October 24th: United Nations Day`,
  `October 29th: International Internet Day`,
  `November 8th: World Town Planning Day`,
  `November 14th: World Diabetes Day`,
  `November 14th: World Philosophy Day`,
  `November 16th: International Day of Tolerance`,
  `November 19th: World Toilet Day`,
  `November 21st: World Television Day`,
  `November 25th: International Day for the Elimination of Violence Against Women`,
  `November 30th: International Computer Security Day`,
  `December 1st: World AIDs Day`,
  `December 2nd: International Day for the Abolition of Slavery`,
  `December 5th: International Volunteers Day`,
  `December 7th: International Civil Aviation Day`,
  `December 10th: Human Rights Day`,
  `Buddhism: Mahayana New Year`,
  `Buddhism: Lunar New Year`,
  `Buddhism: Nirvana Day`,
  `Buddhism: Magha Puja Day`,
  `Buddhism: Theravada Day`,
  `Buddhism: Vesak Buddha Day`,
  `Buddhism: Obon`,
  `Buddhism: Asala - Dharma Day`,
  `Buddhism: Bodhi Day`,
  `Judaism: Tu Bishvat`,
  `Judaism: Purim`,
  `Judaism: Shushan Purim`,
  `Judaism: Passover`,
  `Judaism: Yom Hasshoah`,
  `Judaism: Yom HaZikaron`,
  `Judaism: Yom HaAtzma'ut`,
  `Judaism: Lag BaOmer`,
  `Judaism: Yom Yerushalayim`,
  `Judaism: Shavuot`,
  `Judaism: Tish'a B'Av`,
  `Judaism: Rosh HaShana`,
  `Judaism: Fast of Gedaliah`,
  `Judaism: Yom Kippur`,
  `Judaism: Sukkot`,
  `Judaism: Shmini Atzeret`,
  `Judaism: Hanukkah`,
  `Christianity: Epiphany`,
  `Christianity: The Baptism of Jesus`,
  `Christianity: Candlemas`,
  `Christianity: St. Valentines Day`,
  `Christianity: Ash Wednesday`,
  `Christianity: St. Patrick's Day`,
  `Christianity: St. Joseph's Day`,
  `Christianity: Palm Sunday`,
  `Christianity: Maunday (Holy) Thursday`,
  `Christianity: Good Friday`,
  `Christianity: Easter`,
  `Christianity: St. George's Day`,
  `Christianity: Ascension of Jesus`,
  `Christianity: Pentecost`,
  `Christianity: Saint Vladimir`,
  `Christianity: Trinity Sunday`,
  `Christianity: Corpus Cristi`,
  `Christianity: Saints Peter and Paul`,
  `Christianity: St. James the Great Day`,
  `Christianity: Lammas`,
  `Christianity: The Assumption of Mary`,
  `Christianity: Holy Cross Day`,
  `Christianity: Michael and All Angels`,
  `Christianity: All Hallows Eve`,
  `Christianity: All Saints' Day`,
  `Christianity: All Souls' Day`,
  `Christianity: Thanksgiving`,
  `Christianity: Christ the King`,
  `Christianity: St. Andrew's Day`,
  `Christianity: Advent - First Sunday`,
  `Christianity: St. Nicholas Day`,
  `Christianity: Christmas Eve`,
  `Christianity: Christmas`,
  `Christianity: Holy Innocents`,
  `Christianity: Watch Night`,
  `Hindu: Makarsankranti / Pongal`,
  `Hindu:	Thaipusam`,
  `Hindu: Vasant Panchami`,
  `Hindu: Maha Shivaratri`,
  `Hindu: Holika Dahan`,
  `Hindu: Holi`,
  `Hindu: Hindu New Year`,
  `Hindu: Ugadi / Gudi Padwa / Telugu New Year`,
  `Hindu: Ramanavami`,
  `Hindu: Tamil New Year`,
  `Hindu: Bengali New Year`,
  `Hindu: Vaisakhi / Baisakhi / Vishu`,
  `Hindu: Hanuman Jayanti`,
  `Hindu: Akshaya Tritiya`,
  `Hindu: Savitri Pooja`,
  `Hindu: Puri Rath Yatra`,
  `Hindu:	Guru Purnima`,
  `Hindu: Nag Panchami`,
  `Hindu: Varalakshmi Vrat`,
  `Hindu:	Raksha Bandhan`,
  `Hindu:	Krishna Janmashtami`,
  `Hindu: Ganesh Chaturthi`,
  `Hindu: Onam`,
  `Hindu: Vishwakarma Puja`,
  `Hindu: Mahalaya Amavasya`,
  `Hindu: Navaratri`,
  `Hindu: Dusshera`,
  `Hindu: Sharad Purnima`,
  `Hindu: Karwa Chauth`,
  `Hindu:	Dhan Teras`,
  `Hindu:	Diwali`,
  `Hindu: Bhai Dooj`,
  `Hindu: Chhath Puja`,
  `Hindu: Kartik Poornima`,
  `Hindu: Geeta Jayanti`,
  `Hindu: Dhanu Sankranti`,
  `Islam: Lailat al Miraj`,
  `Islam: Lailat al Bara'ah`,
  `Islam: Ramadan`,
  `Islam: Laylat al Qadr`,
  `Islam:	Waqf al Arafa - Hajj`,
  `Islam: Eid-al-Fitr`,
  `Islam: Hijra`,
  `Islam:	Day of Ashura / Muharram`,
  `Islam:	Milad un Nabi`,
  `Sikh: Guru Gobind Singh Birthday`,
  `Sikh: Maghi - Lohri`,
  `Sikh: Holi`,
  `Sikh: Hola Mohalla`,
  `Sikh: Vaisakhi`,
  `Sikh: Birthday of Guru Angad Dev`,
  `Sikh: Martyrdom of Guru Arjan Dev Sahib`,
  `Sikh: Birth of the Guru Granth`,
  `Sikh: Diwali`,
  `Sikh: Guru Nanak Birthday`,
  `Sikh: Martyrdom of Guru Tegh Bahadur Sahib`,
  `November 26th: Mongolian Constitution Day`,
  `January 26th: Australia Day`,
  `January 26th: Republic Day in India`,
  `February 6th: Waitangi Day in New Zealand`,
  `February 11th: National Foundation Day in Japan`,
  `March 1st: Independence Movement Day in South Korea`,
  `March 12th: Independence & Republic Day in Mauritius`,
  `March 17th: St. Patrick's Day in Ireland`,
  `March 25th: Independence Day in Greece`,
  `April 27th: Freedom Day in South Africa`,
  `May 17th: Constitution Day in Norway`,
  `May 25th: National Day/May 1810 Revolution in Argentina`,
  `June 2nd: Republic Day in Italy`,
  `June 5th: Constitution Day in Denmark`,
  `June 6th: National Day in Sweden`,
  `June 12th:	Independence Day in Philippines`,
  `June 12th: Russia Day`,
  `July 1st: Spl Admin. Region Establishment Day in Hong Kong`,
  `July 5th: Independence Day in Algeria`,
  `July 14th: Bastille Day in France`,
  `July 20th: Independence Day in Colombia`,
  `July 21st: Belgian National Day`,
  `July 23rd: Revolution Day in Egypt`,
  `August 9th: National Day in Singapore`,
  `August 15th: Liberation Day in South Korea`,
  `August 15th: Independence Day in India`,
  `August 17th: Independence Day in Indonesia`,
  `August 31st: National Day in Malaysia`,
  `September 2nd: Independence Day in Vietnam`,
  `September 7th: Independence Day in Brasil`,
  `September 16th: Independence Day in Mexico`,
  `October 1st: National Day in Hong Kong`,
  `October 1st: National Day in the People's Republic of China`,
  `October 3rd: Unity Day in Germany`,
  `October 12th: Hispanic Day in Spain`,
  `October 29th: Republic Day in Turkey`,
  `November 15th: Republic Day in Brasil`,
  `December 1st: National Day in Romania`,
  `December 2nd: National Day in United Arab Emirates`,
  `December 5th: The Present King's Birthday in Thailand`,
  `December 12th: Jamhuri Day in Kenya`,
  `August 6th: Jamaican Independence Day`,
  `July 28th: Independence Day in Peru`
];
